# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. 

Vagrant.configure(2) do |config|

  #Denis adicionei isso aqui https://github.com/vagrant-libvirt/vagrant-libvirt/issues/574
 # ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

 # VAGRANT_LOG=debug 
 # VAGRANT_DEFAULT_PROVIDER=libvirt

  config.vm.box = "jenkins"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder.
  config.vm.synced_folder "../../jenkins", "/home/vagrant/jenkins", create: true

end
